#Nome da aplicação
spring.application.name=agendador-tarefas

#URL do banco de dados não relacional MongoDB
spring.mongodb.uri=mongodb://localhost:27017/db_agendador

#URL do microserviço Usuarios
usuario.url=localhost:8080

#Porta para rodar a aplicação, pois o MS Usuario está na padrão 8080
server.port=8081