#Nome da aplicaçao
spring.application.name=agendador-tarefas

#URL do banco de dados nao relacional MongoDB
spring.mongodb.uri=mongodb://localhost:27017/db_agendador

#URL para acessar o container do MongoDb quando Dockerizado - já configurado no .jar
#spring.mongodb.uri=mongodb://host.docker.internal:27017/db_agendador

#URL do microserviço Usuarios
usuario.url=localhost:8080

#Porta para rodar a aplicaçao, pois o MS Usuario esta na padrao 8080
server.port=8081