#Nome da aplicaÃ§ao
spring.application.name=agendador-tarefas

#URL do banco de dados nao relacional MongoDB para rodar localmente
#spring.mongodb.uri=mongodb://localhost:27017/db_agendador

#URL para acessar o container do MongoDb quando Dockerizado
spring.mongodb.uri=mongodb://mongo:27017/db_agendador

#URL do microserviÃ§o Usuarios
usuario.url=http://usuario:8080

#Porta para rodar a aplicaÃ§ao, pois o MS Usuario esta na padrao 8080
server.port=8081

jwt.secret=YzNWaExXTm9ZWFpsTFhObFkzSmxkR0V0YzNWd1pYSXRjMlZuZFhKaExYRjFaUzFrWlhabExYTmxjaTFpWlcwdGJHOXVaMkU9